export const GENRES = [
  { value: 'ACTION', label: 'Action' },
  { value: 'ADVENTURE', label: 'Adventure' },
  { value: 'ANIMATION', label: 'Animation' },
  { value: 'BIOGRAPHY', label: 'Biography' },
  { value: 'COMEDY', label: 'Comedy' },
  { value: 'CRIME', label: 'Crime' },
  { value: 'DRAMA', label: 'Drama' },
  { value: 'FAMILY', label: 'Family' },
  { value: 'FANTASY', label: 'Fantasy' },
  { value: 'HISTORY', label: 'History' },
  { value: 'HORROR', label: 'Horror' },
  { value: 'MUSIC', label: 'Music' },
  { value: 'MUSICAL', label: 'Musical' },
  { value: 'MYSTERY', label: 'Mystery' },
  { value: 'ROMANCE', label: 'Romance' },
  { value: 'SCI_FI', label: 'Sci-Fi' },
  { value: 'THRILLER', label: 'Thriller' },
  { value: 'WAR', label: 'War' },
  { value: 'WESTERN', label: 'Western' },
];
